on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [connect-pattern, custom-adapter-and-fake, extending-connect-adapters, developing-openai-plugins, using-connect-adapters]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - run: pushd ${{ matrix.project }} && ./gradlew test
      - name: Tag automerge branch
        if: ${{ startsWith(env.GITHUB_HEAD_REF, 'auto') && github.event_name == 'pull_request' }}
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
