on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ connect-pattern, custom-api-client-and-fake, extending-connect-api-clients, using-connect-api-clients ]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - run: pushd ${{ matrix.project }} && ./gradlew test
  label:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Tag automerge branch
        if: ${{ github.event_name == 'pull_request' }}
        uses: TimonVS/pr-labeler-action@v5.0.0
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
