on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [connect-pattern, custom-adapter-and-fake, extending-connect-adapters, using-connect-adapters]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - run: pushd ${{ matrix.project }} && ./gradlew test
