on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [connect-pattern, custom-adapter-and-fake, using-connect-adapters]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: pushd ${{ matrix.project }} && ./gradlew test
