on:
  push:
    branches:
      - '*'
jobs:
  build-all-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: pushd using-connect-adapters && ./gradlew test && popd
      - run: pushd custom-adapter && ./gradlew test && popd
      - run: pushd custom-adapter-with-codegen && ./gradlew test && popd
